### ISSUE TITLE
Config app only accepts whole numbers

### ISSUE THREAD

**Issue by ImAHungryMan** [Raptor831/RFStockalike#34]
I apologize if this is the wrong place for this.

The RFStockalike config app won't accept values with decimals for mass and thrust. Is this intended? It makes diversifying RCS thrusters somewhat difficult. And it would be nice to have for larger engines if only for the ability to fine-tune TWR.

**Comment by Raptor831** [comment]
That can be fixed quite easily. I was limiting that for some good reason, which I can't remember now. Mass can be defined in up to kilograms (.001 mass units), so that should be working now. Thrust was limited I believe to keep from splitting hairs.

How fine of control would be appropriate? Going to hundredths seems a bit much for thrust, but I could see the need for RCS and/or electric propulsion (if we're talking realistic values).

**Comment by ImAHungryMan** [comment]
My main concern I think was that thrust scaling with RCS (or other low-thrust engines) doesn't work very well. For example, a thrust value of one would result in zero thrust for certain propellants. Otherwise, I see your point about the need to avoid splitting hairs. RFStockalike /= RealismOverhaul. Your approach will probably make balancing easier.

How about setting it to tenths to give the config generator a bit more room to play with? For anything fancier, I figure I'll just do the math myself.

**Comment by Raptor831** [comment]
The math behind the scenes does its thing with at least 3 decimal places accuracy (IIRC). So, if you set an RCS thrust of 1, you should get say something like .58 kN thrust for certain mixtures, and like .98 for MMH/N2O4.

When I built the app, I just didn't see a reason to allow .001 kN increments since we were talking larger engines and not RCS. Now that RCS is in play, I don't think it's a bad idea to add decimals in. We can try to 3 decimal places like the mass, since that's more than enough I think. I'll put that on the list.

**Comment by ImAHungryMan** [comment]
Thanks!

**Comment by Raptor831** [comment]
Should be fixed now.
