### ISSUE TITLE
Stockalike_SpaceY.cfg needs updating

### ISSUE THREAD

**Issue by LebedevRI** [Raptor831/RFStockalike#47]
As per https://github.com/NathanKell/ModularFuelSystem/issues/98#issuecomment-148388752,
looks like [https://github.com/Raptor831/RFStockalike/blob/master/GameData/RealFuels-Stockalike/Stockalike_SpaceY.cfg](Stockalike_SpaceY.cfg) uses wrong type - `ModuleEngines` - instead of `ModuleEnginesRF`, like every other config does.

As a result,. for those engines, ullage and ignition limiting does not function.

**Comment by Raptor831** [comment]
Yeah, those should just need adjusting to use ModuleEnginesRF. They will lose effects, unless they were MEFX, though, or unless they have some other EFFECTS{} node set up.

**Comment by LebedevRI** [comment]
@Raptor831 
Hmm, can i help somehow?

**Comment by Raptor831** [comment]
Not unless you'd like to update all of the engines to use ModuleEnginesRF and add ignition values. Normally I'd just re-generate from the web-app info, but since we've tried to keep the various modes in play (i.e. the Merlin-type cluster engine), it has to be done by hand.

But I'm always happy to have some help, if you'd like. Otherwise this will just be on my next to-do list.

**Comment by LebedevRI** [comment]
@Raptor831 
Okay, i can at least try :)
(WIP, i'll PR when i think it's anywhere near ready) https://github.com/Raptor831/RFStockalike/compare/master...LebedevRI:update-SpaceY_cfg
Question:
1. If engine is already `type = ModuleEnginesFX`, should i also change it to `type = ModuleEnginesRF`?
2. Based on current diff, is there anything i'm doing wrong already?

**Comment by Raptor831** [comment]
1. Yes, in order to get ullage and ignition, you must use the ModuleEnginesRF module. MEFX doesn't cut it, unfortunately.
2. Looks like you're heading in the right direction to me. :+1:
