### ISSUE TITLE
Conflict with RO_RCS_Config.cfg

### ISSUE THREAD

**Issue by Bornholio** [Raptor831/RFStockalike#94]
When loaded these configs give warnings and 2 errors due to changes in RO's RCS system.
RF is forced to install the configs by CKAN.

WRN 20:03:39.584] [ModuleManager] Cannot find key thrusterPower in CONFIG
[ERR 20:03:39.587] [ModuleManager] Error - Cannot parse variable search when replacing (%) key maxThrust = #$thrusterPower$
[WRN 20:03:39.589] [ModuleManager] Cannot find key thrusterPower in CONFIG
[ERR 20:03:39.591] [ModuleManager] Error - Cannot parse variable search when replacing (%) key minThrust = #$thrusterPower$

**Comment by Raptor831** [comment]
When RO is installed cleanly through CKAN, though, it should install the RO configs and not the Stockalike configs. Last I checked RO wasn't fully updated so you had to piecemeal a CKAN install, which means Stockalike gets installed with RF. If that's still the case, I'd recommend just deleting the RFStockalike folders since they conflict with RO anyway.

**Comment by Bornholio** [comment]
closing until i have a gooder solution

**Comment by Raptor831** [comment]
Well, would setting a :HAS[!RealismOverhaul] on all of my configs do the trick? There's many of the RO ones that have the :HAS[!RealFuels_StockEngines] in them, so having the check on both ends would be safer. Plus, that's not terribly hard for me to find/replace in my editors either. XD It's at least the ok, in case CKAN goes weird again or someone manually goofs this up, it won't break the world.

**Comment by Bornholio** [comment]
Yes i think it would. tag me to test it if you make the change.
